### ISSUE TITLE
Disable/Enable Certain Datapoints

### ISSUE THREAD

**Issue by tyetenna** [mewtek/MistWX-i2ME#3]
It would be nice to be able to disable and enable certain datapoints in the event the user has a custom configuration in their environment which requires data to be brought in differently than the encoder is current set up. (i.e Enable Alerts and Current Conditions, but disable all other data from being sent)

**Comment by mewtek** [comment]
Weirdly enough, this also involved making the generation in bursts, which might make traffic a little less aggressive on the UDP ports for the i2.

Implemented in https://github.com/mewtek/MistWX-i2ME/commit/dce86d1ae6b51c2981841cde5d24e1ba4ddcbb1a
